name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Install latest Docker
      run: curl -fsSL https://get.docker.com | sudo sh
    - name: Build Docker image
      run: docker build -t openfang .
    - name: Build openfang
      run: docker run -v $(pwd)/output:/output openfang
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: openfang-${{ github.sha }}
        path: output/
